clear; clc;
% dataset related arguments
dataset_name = 'ml1m';
phase = 'validation';
rate_once = 1;
L = 5;
T = 3;

% training arguments
seed = 1234;
n_iter = 50;
learning_rate = 1e-3;
l2 = 1e-6;
neg_samples = 3; % per targets
early_stop = true;

% Caser related arguments
d = 50;
nv = 4;
nh = 16;
ac_conv = 'relu';
ac_fc = 'relu'; 
drop_rate = 0.5;

args = struct(...
        'dataset',dataset_name,...
        'phase',phase,...    
        'rateonce',rate_once,...    
        'L',L,...
        'T', T,...
        'seed',seed,...
        'niter',n_iter,...
        'lrate',learning_rate,...
        'l2',l2,...
        'negsample',neg_samples,...    
        'earlystop',early_stop,...    
        'd',d,...
        'nv',nv,...                
        'nh',nh,...
        'acconv',ac_conv,...
        'acfc',ac_fc,...
        'droprate',drop_rate...
        );

caser_train(args);
